### ISSUE TITLE
Reference tab labels look weird on smaller viewports

### ISSUE THREAD

**Issue by samuel-zuk** [engaging-computing/MYR#257] opened 2019-06-20 20:22 UTC
example:
![Screenshot from 2019-06-20 15-34-14](https://user-images.githubusercontent.com/50585524/59878934-8c8db800-9377-11e9-80f7-6e137baa8924.png)

**Comment by jasondkiesling** [comment] 2019-06-20 20:23
Duplicate of #213

**Closed by jasondkiesling** 2019-06-20 20:23 UTC
Labels: Frontend, Reference, bug
